### PR TITLE
Add type hints for some of the major classes

### PR DESCRIPTION
**Pull request by yck011522**
Addresses #416

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [x] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [ ] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [ ] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas_fab.robots.CollisionMesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by yck011522** [comment]
This is partly address #416

**Comment by yck011522** [comment]
Waiting for #422 to change also the type hints for plan_cartesian_motion.
Waiting for #424 to change the type hints in the backend features.

**Comment by jf---** [comment]
@yck011522 a terrific contribution

**Comment by yck011522** [comment]
blocked by #422

**Comment by yck011522** [comment]
Okay everyone I'm messing everything up with renaming a branch. I hope there isn't any opened review here. I'll make a new PR.

**Pull request closed without merging**
