### PR TITLE
add docker to contribution guide

### PR DESCRIPTION
**Pull request by beverlylytle**
As with roslibpy, I think it makes sense to add how to run the integration tests within the contribution guide.

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [x] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I added a line to the `CHANGELOG.rst` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [ ] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [ ] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas_fab.robots.Configuration`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by beverlylytle** [comment]
oh, i suppose stopping the docker containers should also be listed...

**Review by gonzalocasas — APPROVED** [review]
The change in itself is 👍 
But since you at this, how about we add a single `docker-compose.yml` somewhere under `tests` that starts up MoveIt with the UR5 + VREP all in one go? I put together a first stab at that here:

[integration-tests.zip](https://github.com/compas-dev/compas_fab/files/5958427/integration-tests.zip)

**Comment by beverlylytle** [comment]
Good idea.  Do you mean this docker compose file to be used for local testing or also for the github workflow?

**Comment by gonzalocasas** [comment]
> Good idea. Do you mean this docker compose file to be used for local testing or also for the github workflow?

Ah good point! I thought about local testing, but this would make the github workflow faster (because it does not load the X forwarding part), so using it for both would be great

**Comment by beverlylytle** [comment]
ok, @gonzalocasas, i added your docker-compose file, and it seems to work.  the integration tests are failing because of the `compas.get('faces.obj')` thing

**Review by gonzalocasas — APPROVED** [review]
🚀

**Pull request merged**
