### PR TITLE
Use scale factor for CollisionMesh (suggestion for #142)

### PR DESCRIPTION
**Pull request by tetov**
Suggestion for #142 

### What type of change is this?

Change in a **backwards-compatible** manner.

Not if users are scaling the collision mesh before adding it to scene.

### Checklist

- [x] I added a line to the `CHANGELOG.rst` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [x] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [x] I ran lint on my computer and there are no errors (i.e. `invoke lint`) .
- ~~I have added tests that prove my fix is effective or that my feature works.~~ (Will do that when I write tests for whole module)
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tetov** [comment]
To make it completely backwards compatible we could do something like this:
```python
class CollisionMesh(object):
    """[...]"""
        
    def scale(self, scale_factor):
        """Scales the collision mesh uniformly.

        Parameters
        ----------
        scale_factor : :obj:`float`
            Scale factor. A :class:`compas.geometry.Scale` instance is also accepted for backwords compatibility.
        """
        if ifinstance(scale_factor, Scale):
            # Scale instance accepted to ensure backwards compatibility
            S = scale_factor
        else:
            S = Scale([scale_factor] * 3)

        self.mesh.transform(S)
```

**Comment by romanarust** [comment]
i would go for a breaking change though....

**Comment by tetov** [comment]
Added line to changelog to make it ready for merge :).

**Comment by romanarust** [comment]
Approved! Thanks!

**Pull request merged**
